### ISSUE TITLE
FFNAV_EKF_MakeParams.m

### ISSUE THREAD

**Issue by MunLee001** [Cfrazzle/SRCL_FFNAV#3]
Hi, I can't find FFNAV_EKF_MakeParams.m in 03_FAEKF

**Comment by ct-fraser** [comment]
Hello! I believe there's a copy of FFNAV_EKF_MakeParams.m is contained in 01_EKF, that should contain everything you need, so either copy/paste that file where you want it or add 01_EKF to the path. Hope that help!

**Comment by MunLee001** [comment]
Thank you for your reply!
